/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controller.ClientsController;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JTable;
import javax.swing.table.TableColumn;
import view.components.ButtonEditor;
import view.components.ButtonRenderer;

/**
 *
 * @author david
 */
public class Clients extends javax.swing.JFrame {

    private final ClientsController controller;
    public Clients() 
    {
        initComponents();
        setLocationRelativeTo(null);
        this.controller = new ClientsController(this);
        this.controller.updateTable();
        JButton sampleButton = new JButton("Editar");
        int buttonHeight = sampleButton.getPreferredSize().height + 10; // +10 para margem
        jTable.setRowHeight(buttonHeight);
        // Configurar a coluna Editar
        TableColumn editColumn = jTable.getColumnModel().getColumn(7);
        editColumn.setCellRenderer(new ButtonRenderer("edit"));
        editColumn.setCellEditor(new ButtonEditor(new JCheckBox(), "edit"));

        // Configurar a coluna Excluir
        TableColumn deleteColumn = jTable.getColumnModel().getColumn(8);
        deleteColumn.setCellRenderer(new ButtonRenderer("delete"));
        deleteColumn.setCellEditor(new ButtonEditor(new JCheckBox(), "delete"));

        // Ajustar largura das colunas
        editColumn.setPreferredWidth(80);
        deleteColumn.setPreferredWidth(80);

        // Opcional: remover o cabeçalho das colunas de ação
        jTable.getTableHeader().setReorderingAllowed(false);
    }
    public ClientsController getController() 
    {
        return controller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null, null, null, null, "Editar", "Excluir"},
            {null, null, null, null, null, null, null, "Editar", "Excluir"},
            {null, null, null, null, null, null, null, "Editar", "Excluir"},
            {null, null, null, null, null, null, null, "Editar", "Excluir"}
        },
        new String [] {
        "ID", "Nome", "Endereço", "CEP", "Telefone", "RG", "DT_Nascimento", "Editar", "Excluir"
        }
    )  {
    @Override
    public boolean isCellEditable(int row, int column) 
    {
        // Tornar editáveis apenas as colunas de botões
        return column == 7 || column == 8;
    }
    });
        jScrollPane1.setViewportView(jTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 50, 610, 270));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/principal_menu.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clients().setVisible(true);
            }
        });
    }

    public JTable getjTable() {
        return jTable;
    }

    public void setjTable(JTable jTable) {
        this.jTable = jTable;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
}
