/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controller.ClientController;
import Controller.ClientsController;
import Controller.CreateClientController;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JTable;
import javax.swing.table.TableColumn;
import view.components.ButtonEditor;
import view.components.ButtonRenderer;

/**
 *
 * @author david
 */
public class Clients extends javax.swing.JFrame {

    private final CreateClientController createclientcontroller;
    private final ClientsController controller;
    private final ClientController clientcontroller;
    private final view.CreateClient createclientview;
    public Clients() 
    {
        initComponents();
        setLocationRelativeTo(null);
        view.Client clientview = new Client(this);
        this.clientcontroller = new ClientController(clientview, this);
        this.createclientview = new view.CreateClient(this);
        this.controller = new ClientsController(this);
        this.createclientcontroller = new CreateClientController(createclientview, this);
        this.controller.updateTable();
        JButton sampleButton = new JButton("Editar");
        int buttonHeight = sampleButton.getPreferredSize().height + 5; // +5 para margem
        jTable.setRowHeight(buttonHeight);
        // Configurar a coluna Editar
        TableColumn editColumn = jTable.getColumnModel().getColumn(7);
        editColumn.setCellRenderer(new ButtonRenderer("edit"));
        editColumn.setCellEditor(new ButtonEditor(new JCheckBox(), "edit", this, clientview));

        // Configurar a coluna Excluir
        TableColumn deleteColumn = jTable.getColumnModel().getColumn(8);
        deleteColumn.setCellRenderer(new ButtonRenderer("delete"));
        deleteColumn.setCellEditor(new ButtonEditor(new JCheckBox(), "delete", this, clientview));

        // Ajustar largura das colunas
        editColumn.setPreferredWidth(80);
        deleteColumn.setPreferredWidth(80);

        // Opcional: remover o cabeçalho das colunas de ação
        jTable.getTableHeader().setReorderingAllowed(false);
    }
    public ClientController getController() 
    {
        return clientcontroller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton.setBackground(new java.awt.Color(0, 153, 51));
        jButton.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jButton.setForeground(new java.awt.Color(255, 255, 255));
        jButton.setText("Novo Cliente");
        jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, -1, -1));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Endereço", "CEP", "Telefone", "RG", "DT_Nascimento", "Editar", "Excluir"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 50, 610, 270));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/principal_menu.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActionPerformed
        createclientcontroller.navegateToCreateClient();
    }//GEN-LAST:event_jButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clients().setVisible(true);
            }
        });
    }

    public JTable getjTable() {
        return jTable;
    }

    public void setjTable(JTable jTable) {
        this.jTable = jTable;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
}
